# Generated by Django 4.0.6 on 2022-07-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('blood_group', models.CharField(default='A+', max_length=4)),
            ],
        ),
    ]
